US015: ParkingSlot Create Action
iamurtazo/ParkingZoneApp pull request #16
Opened 2024-05-07 10:17 UTC by iamurtazo

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper requested changes

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper commented on ParkingSlots.Tests/Controller/ParkingSlotControllerTests.cs
> +        var model = ((ViewResult)create).Model;
In Act part why are you taking model
It should be in Assert part
var model = Assert.IsType<ViewResult>(create).Model;

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper commented on ParkingSlots.Tests/Controller/ParkingSlotControllerTests.cs
>          var model = ((ViewResult)index).Model;
In Act part why are you taking model
It should be in Assert part
var model = Assert.IsType(create).Model;

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper commented on ParkingSlots.Tests/Controller/ParkingSlotControllerTests.cs
> +        var model = create as RedirectToActionResult;
Same

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper commented on ParkingSlots.Tests/Models/CreateViewModelTest.cs
> +        Assert.Equal(expected, result);
It is better if you use JsonSerializer

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper commented on ParkingZoneApp.Tests/Controller/ParkingZoneControllerTests.cs
>              var details = _parkingZoneController.Details(_parkingZones[0].Id);
var result

2024-05-07 12:39 UTC, SamanKingDotNetDeveloper commented on ParkingZoneApp/ViewModels/ParkingSlotViewModels/ListOfParkingSlotsVM.cs
>          {
let's make it beautiful anyway it is not in use
public ListOfParkingSlotsVM() {   }

2024-05-07 19:16 UTC, SamanKingDotNetDeveloper approved these changes

2024-05-08 05:16 UTC, dotnetdew requested changes

2024-05-08 05:16 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controller/ParkingZoneControllerTests.cs
>              var details = _parkingZoneController.Details(_parkingZones[0].Id);
```suggestion
            var result = _parkingZoneController.Details(_parkingZones[0].Id);
```

2024-05-08 05:16 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingSlot/Create.cshtml
> +                </select>
lets make it checkbox if not checked false, if checked true

2024-05-08 05:16 UTC, dotnetdew commented on ParkingZoneApp/Models/ParkingSlot.cs
> +[Table("ParkingSlots")]
you dont need it because you specified in DbContext

2024-05-08 05:16 UTC, dotnetdew commented on ParkingZoneApp/Models/ParkingZone.cs
> +[Table("ParkingZones")]
you dont need it because you specified in DbContext

2024-05-08 05:16 UTC, dotnetdew commented on ParkingSlots.Tests/Controller/ParkingSlotControllerTests.cs
> +    }
we dont need this test because you have done in model test

2024-05-08 10:15 UTC, dotnetdew approved these changes

2024-05-08 10:16 UTC, merged